sudo: required
services:
  - docker

before intsall:
  - docker build -t pipeline -f Dockerfile.dev .

script:
  - docker run pipeline npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker_react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-033211137270"
  bucket_path: "docker_react"

  on:
    branch: master
  access_key_id: $AWS_Access key
  secret_access_key: 
    secure: "SECRET_key"